// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TurretOwner } from "./tables/TurretOwner.sol";
import { OwnerShotOnce } from "./tables/OwnerShotOnce.sol";
